-- exercises_seed.sql — 15 exercícios populares

insert into public.exercises
  (name, slug, muscle_group, muscles_worked, equipment, category,
   difficulty, instructions, tips, free_db_id, rapid_api_id)
values

('Supino Reto com Barra',
 'supino-reto-barra', 'Peito',
 ARRAY['Tríceps','Ombro Anterior'],
 'Barra', 'Empurrão', 'intermediate',
 ARRAY['Deite no banco com os pés apoiados no chão.','Segure a barra com pegada levemente mais larga que os ombros.','Desça a barra de forma controlada até tocar levemente no peito.','Empurre a barra para cima até estender os cotovelos completamente.','Mantenha as escápulas retraídas durante todo o movimento.'],
 ARRAY['Cotovelos a 45–75° do tronco','Não solte a barra bruscamente','Expire ao subir'],
 'Barbell_Bench_Press_-_Medium_Grip', '0025'),

('Supino Inclinado com Halteres',
 'supino-inclinado-halteres', 'Peito',
 ARRAY['Feixe Clavicular do Peitoral','Ombro Anterior'],
 'Halter', 'Empurrão', 'intermediate',
 ARRAY['Ajuste o banco a 30–45°.','Segure um halter em cada mão na altura do peito, com as palmas voltadas para frente.','Pressione os halteres para cima até que os braços estejam quase estendidos.','Desça de forma controlada até o nível do peito.'],
 ARRAY['Ângulo de 30° ativa mais o peitoral que 45°','Gire levemente os pulsos ao subir'],
 'Dumbbell_Incline_Bench_Press', '0303'),

('Crucifixo com Halteres',
 'crucifixo-halteres', 'Peito',
 ARRAY['Peitoral Menor'],
 'Halter', 'Empurrão', 'intermediate',
 ARRAY['Deite no banco plano com um halter em cada mão.','Estenda os braços acima do peito com leve flexão nos cotovelos.','Abra os braços em arco, descendo os halteres até a altura dos ombros.','Traga de volta como se abraçasse uma árvore grande.'],
 ARRAY['Mantenha a leve flexão nos cotovelos constante','Foque no alongamento no ponto mais baixo'],
 'Dumbbell_Flyes', '0284'),

('Puxada Frontal na Máquina',
 'puxada-frontal-maquina', 'Costas',
 ARRAY['Bíceps','Romboides'],
 'Máquina', 'Puxada', 'beginner',
 ARRAY['Sente-se e posicione as coxas sob o apoio.','Segure a barra com pegada pronada, mais larga que os ombros.','Puxe a barra em direção à parte superior do peito, trazendo os cotovelos para baixo.','Pause um segundo ao final e retorne de forma controlada.'],
 ARRAY['Incline levemente o tronco para trás','Não balance o corpo para puxar mais carga'],
 'Front_Lat_Pulldown', '0320'),

('Remada Curvada com Barra',
 'remada-curvada-barra', 'Costas',
 ARRAY['Bíceps','Trapézio','Lombar'],
 'Barra', 'Puxada', 'intermediate',
 ARRAY['Segure a barra com pegada pronada e incline o tronco a ~45°.','Mantenha a coluna neutra com o core ativado.','Puxe a barra em direção ao abdômen inferior, retraindo as escápulas.','Desça a barra até os braços estarem estendidos.'],
 ARRAY['Evite usar a lombar para puxar','Cotovelos próximos ao corpo para foco no dorsal'],
 'Barbell_Bent_Over_Row', '0032'),

('Puxada com Pegada Supinada',
 'puxada-supinada', 'Costas',
 ARRAY['Bíceps','Infraespinal'],
 'Barra', 'Puxada', 'intermediate',
 ARRAY['Segure a barra com pegada supinada (palmas para você), na largura dos ombros.','Puxe o peito em direção à barra, trazendo os cotovelos ao lado do tronco.','Desça de forma controlada até os braços estenderem completamente.'],
 ARRAY['Pegada supinada recrutará mais bíceps que a pronada'],
 'Underhand_Cable_Pulldowns', '0651'),

('Desenvolvimento Militar com Barra',
 'desenvolvimento-militar-barra', 'Ombro',
 ARRAY['Tríceps','Trapézio Superior'],
 'Barra', 'Empurrão', 'intermediate',
 ARRAY['Em pé (ou sentado), segure a barra na frente do pescoço, na altura dos ombros.','Pressione a barra para cima até os braços estenderem.','Desça de forma controlada até o ponto de partida.'],
 ARRAY['Core contraído para proteger a lombar','Não hiperestenda o pescoço ao subir'],
 'Barbell_Military_Press', '0052'),

('Elevação Lateral com Halteres',
 'elevacao-lateral-halteres', 'Ombro',
 ARRAY['Deltóide Médio'],
 'Halter', 'Empurrão', 'beginner',
 ARRAY['Em pé, segure um halter em cada mão ao lado do corpo.','Eleve os braços lateralmente até a altura dos ombros, com leve flexão no cotovelo.','Desça de forma controlada.'],
 ARRAY['Incline levemente o tronco para frente','Controle a descida — o excêntrico importa'],
 'Dumbbell_Lateral_Raise', '0290'),

('Agachamento Livre com Barra',
 'agachamento-livre-barra', 'Quadríceps',
 ARRAY['Glúteos','Isquiotibiais','Core','Lombar'],
 'Barra', 'Pernas', 'intermediate',
 ARRAY['Posicione a barra nos trapézios ou no nível dos ombros (low bar).','Afaste os pés na largura dos ombros, pontas voltadas levemente para fora.','Desça controlando o joelho alinhado com o segundo dedo do pé.','Desça até a dobra do quadril ficar abaixo do nível do joelho (full squat).','Empurre o chão e suba mantendo o peito alto.'],
 ARRAY['Respire fundo antes de descer (Valsalva)','Não deixe os joelhos colapsarem para dentro'],
 'Barbell_Full_Squat', '0043'),

('Leg Press 45°',
 'leg-press-45', 'Quadríceps',
 ARRAY['Glúteos','Isquiotibiais'],
 'Máquina', 'Pernas', 'beginner',
 ARRAY['Ajuste o banco e posicione os pés na plataforma na largura dos ombros.','Desbloqueie a máquina e desça a plataforma de forma controlada.','Desça até os joelhos formarem ~90°.','Empurre de volta sem travar os joelhos no topo.'],
 ARRAY['Pés mais altos = mais glúteos; mais baixos = mais quadríceps','Não eleve os glúteos do banco'],
 'Leg_Press', '0388'),

('Stiff com Halteres',
 'stiff-halteres', 'Isquiotibiais',
 ARRAY['Glúteos','Lombar'],
 'Halter', 'Pernas', 'intermediate',
 ARRAY['Em pé, segure um halter em cada mão à frente das coxas.','Incline o tronco para frente com a coluna neutra, descendo os halteres.','Sinta o alongamento nos isquiotibiais até ~45–60°.','Contraia os glúteos ao retornar à posição inicial.'],
 ARRAY['Joelhos levemente flexionados','Não arredonde a lombar','Desça somente até onde a flexibilidade permitir'],
 'Dumbbell_Romanian_Deadlift', '0329'),

('Cadeira Extensora',
 'cadeira-extensora', 'Quadríceps',
 ARRAY[]::text[],
 'Máquina', 'Pernas', 'beginner',
 ARRAY['Ajuste o encosto e o apoio de tornozelo.','Estenda as pernas até quase travar os joelhos.','Retorne de forma lenta e controlada.','Mantenha os glúteos apoiados durante o movimento.'],
 ARRAY['Movimento de isolamento — ideal para finalizar o treino de pernas'],
 'Leg_Extensions', '0389'),

('Rosca Direta com Barra',
 'rosca-direta-barra', 'Bíceps',
 ARRAY['Braquial','Braquiorradial'],
 'Barra', 'Puxada', 'beginner',
 ARRAY['Em pé, segure a barra com pegada supinada na largura dos ombros.','Mantenha os cotovelos junto ao tronco.','Flexione os cotovelos, trazendo a barra até a altura dos ombros.','Desça de forma controlada.'],
 ARRAY['Não balance o tronco','Cotovelos fixos = isolamento máximo'],
 'Barbell_Curl', '0037'),

('Tríceps Testa com Barra EZ',
 'triceps-testa-barra-ez', 'Tríceps',
 ARRAY[]::text[],
 'Barra', 'Empurrão', 'intermediate',
 ARRAY['Deite no banco e segure a barra EZ com pegada pronada.','Com os braços estendidos acima do peito, incline-os levemente para trás.','Flexione os cotovelos até a barra quase tocar a testa.','Estenda os cotovelos retornando à posição inicial.'],
 ARRAY['Cotovelos apontando para o teto','Não abra os cotovelos para os lados'],
 'EZ-Bar_Skullcrusher', '0275'),

('Prancha Abdominal',
 'prancha-abdominal', 'Core',
 ARRAY['Transverso Abdominal','Lombar','Glúteos'],
 'Peso Corporal', 'Core', 'beginner',
 ARRAY['Apoie os antebraços e as pontas dos pés no chão.','Mantenha o corpo em linha reta da cabeça aos calcanhares.','Contraia o abdômen e os glúteos durante toda a duração.','Respire normalmente e evite prender o ar.'],
 ARRAY['Não deixe os quadris subir ou afundar','Olhe para baixo para manter o pescoço neutro'],
 'Plank', null);
